// build.js — concatenates src/ into one file per world. No dependencies.
//
// Why a build step at all: Chrome injects a JS file that is listed in two
// content_scripts entries only ONCE per frame (de-duplicated by path, ignoring
// the world), so the shared modules cannot simply be listed in both the MAIN
// and the isolated entry. Each world gets a single generated file instead.
//
//   node build.js          build once
//   node build.js --watch  rebuild on every change under src/
//
// Edit src/, never dist/.
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const DIST = path.join(__dirname, 'dist');
const SHARED = ['netflix.js', 'util.js', 'bridge.js'];
const BUNDLES = {
  'page.js': [...SHARED, 'page-hook.js'], // MAIN world
  'ext.js': [...SHARED, 'subtitles.js', 'clock.js', 'overlay.js', 'content.js'], // isolated world
};

function build() {
  fs.mkdirSync(DIST, { recursive: true });
  for (const [out, files] of Object.entries(BUNDLES)) {
    const parts = files.map((f) => `// ===== src/${f} =====\n${fs.readFileSync(path.join(SRC, f), 'utf8')}`);
    fs.writeFileSync(path.join(DIST, out), `// GENERATED by build.js from src/ — edit src/, then run: npm run build\n\n${parts.join('\n')}`);
    console.log(`${new Date().toLocaleTimeString()}  dist/${out}  <-  ${files.join(' + ')}`);
  }
}

build();
if (process.argv.includes('--watch')) {
  let pending = null;
  fs.watch(SRC, () => {
    clearTimeout(pending);
    pending = setTimeout(() => { try { build(); } catch (err) { console.error(err); } }, 100);
  });
  console.log('watching src/ ...');
}
